#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Copyright (C) 2020  Marius Rieder <marius.rieder@durchmesser.ch>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


def bake_veeam_o365(opsys, conf, conf_dir, plugins_dir):
    shutil.copy2(cmk.utils.paths.local_agents_dir + "/windows/plugins/veeam_o365_status.ps1",
                 plugins_dir + "/veeam_o365_status.ps1")


bakery_info['veeam_o365'] = {
    'bake_function': bake_veeam_o365,
    'os': ['windows'],
}
