#!/usr/bin/env python
# -*- encoding: utf-8; py-indent-offset: 4 -*-
#
# Copyright (C) 2020  Marius Rieder <marius.rieder@durchmesser.ch>
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

# <<<veeam_o365licenses:sep(9) >>>
# Valid	28.06.2020 02:00:00	2592000	42	50000


def inventory_veeam_o365licenses(info):
    for index, line in enumerate(info):
        yield str(index), {}


def check_veeam_o365licenses(item, params, info):
    if int(item) > len(info):
        yield 3, 'License not found.'
        return

    license_state, license_date, license_validity, \
        license_used, license_total = info[int(item)]

    if license_state == 'Valid':
        yield 0, 'License is vaild till %s' % license_date
    else:
        yield 2, 'License is %s' % license_state


    yield check_levels(savefloat(license_validity),
                       None,
                       (None, None) + params.get('validity', (None, None)),
                       human_readable_func=get_age_human_readable,
                       infoname='Period of validity')

    yield license_check_levels(saveint(license_total), saveint(license_used),
                               params.get('licenses', None))


check_info['veeam_o365licenses'] = {
    'inventory_function': inventory_veeam_o365licenses,
    'check_function': check_veeam_o365licenses,
    'service_description': 'VEEAM O365 License %s',
    'has_perfdata': True,
    'group': 'veeam_o365licenses',
    'includes': ['license.include']
}
