#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# Copyright (C) 2020 Marius Rieder <marius.rieder@durchmesser.ch> - License: GNU General Public License v2

# <<<veeam_o365licenses:sep(9) >>>
# Valid	28.06.2020 02:00:00	42	50000

def inventory_veeam_o365licenses(info):
  for index, line in enumerate(info):
    yield index, {}

def check_veeam_o365licenses(item, params, info):
    if item > len(info):
        yield 3, 'License not found.'
        return

    license_state, license_date, license_used, license_total = info[item]

    if license_state == 'Valid':
        yield 0, 'License is vaild till %s' % license_date
    else:
        yield 2, 'License is %s' % license_state

    yield license_check_levels(saveint(license_total), saveint(license_used), params)

check_info['veeam_o365licenses'] = {
    'inventory_function': inventory_veeam_o365licenses,
    'check_function': check_veeam_o365licenses,
    'service_description': 'VEEAM O365 License %s',
    'has_perfdata': True,
    'group': 'veeam_o365licenses',
    'includes': ['license.include']
}
